[alias]
xtask = "run --package xtask --"

[build]
target-dir = "target"

[target.riscv64gc-unknown-none-elf]
linker = "rust-lld"

[target.loongarch64-unknown-none-softfloat]
linker = "rust-lld"

[target.loongarch64-unknown-none]
linker = "rust-lld"
