[package]
name = "tx-kernel-riscv64-m1dock-mock"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
tx-hal = { path = "../../crates/tx-hal" }
tx-hal-riscv64-m1dock-mock = { path = "../tx-hal-riscv64-m1dock-mock" }
tx-kernel = { path = "../../crates/tx-kernel" }

[[bin]]
name = "tx-kernel-riscv64-m1dock-mock"
path = "src/main.rs"
test = false
doctest = false
