//! Effect type returned by the line discipline input pipeline.
//!
//! `LdiscInputEffect` is the discriminated result of `process_input_byte`.
//! It tells the caller what happened to the byte, without the ldisc itself
//! touching processes, signals, or reactor primitives.

/// Effect produced by processing one input byte through the N_TTY line
/// discipline.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum LdiscInputEffect {
    /// The byte was absorbed without producing user-visible data.
    ///
    /// Covers: bytes buffered into `cooked_buf` before a line commit; VERASE
    /// / VKILL editing; flow-control bytes absorbed while output is stopped;
    /// VLNEXT escape activation.
    Absorbed,

    /// A byte was appended directly to `input_queue` (non-canonical mode).
    ///
    /// Caller should fire `TtyIdentity::input_readable`.
    QueuedForRead,

    /// A cooked-mode line was flushed from `cooked_buf` to `input_queue`.
    ///
    /// Caller should fire `TtyIdentity::input_readable`. Semantically
    /// equivalent to `QueuedForRead` from the caller's perspective but
    /// distinct for observability and for VEOF-on-empty-line detection in
    /// Phase C.
    LineCommitted,

    /// `ISIG` matched a control character. Caller should dispatch a signal to
    /// the controlling tty's foreground process group.
    ///
    /// The line discipline does not post the signal itself; it returns the
    /// signal kind and leaves `deliver_posix_signal` to the caller
    /// (`step_ingest` in Phase C).
    SignalFgPgrp(SignalKind),

    /// Flow-control transition (`IXON` matched VSTOP or VSTART).
    ///
    /// Caller may pause or resume transport TX accordingly.
    FlowControl(FlowCtl),
}

/// The subset of POSIX signals that the N_TTY line discipline can generate.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum SignalKind {
    /// SIGINT — generated by `c_cc[VINTR]` (default: ^C / 0x03).
    Int,
    /// SIGQUIT — generated by `c_cc[VQUIT]` (default: ^\ / 0x1c).
    Quit,
    /// SIGTSTP — generated by `c_cc[VSUSP]` (default: ^Z / 0x1a).
    Tstp,
}

/// Flow control transition direction.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum FlowCtl {
    /// Output stopped (VSTOP received with IXON enabled).
    Stop,
    /// Output resumed (VSTART received, or any character received with IXANY).
    Start,
}
