[package]
name = "tx-substrate"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
tx-hal          = { path = "../tx-hal" }
tx-observe      = { path = "../tx-observe" }
tx-observe-types = { path = "../tx-observe-types" }

[features]
layout-probe = []

[dev-dependencies]
static_assertions = "1.1"

[lib]
path = "src/lib.rs"
test = false
doctest = false

[lints]
workspace = true
