use std::fs;
use std::path::{Path, PathBuf};

use crate::Result;
use crate::util::{copy_dir_contents, optional_option_value, resolve_path};

pub(crate) fn submit(root: &Path, args: Vec<String>) -> Result<()> {
    let Some(kind) = args.first() else {
        return Err("submit command needs `k210`".into());
    };
    match kind.as_str() {
        "k210" => submit_k210(root, &args[1..]),
        other => Err(format!("unknown submit kind '{other}', expected k210")),
    }
}

fn submit_k210(root: &Path, args: &[String]) -> Result<()> {
    let out = optional_option_value(args, "--out")
        .map(PathBuf::from)
        .map(|path| resolve_path(root, path))
        .unwrap_or_else(|| root.join("target").join("submit").join("k210"));
    let dry_run = args.iter().any(|arg| arg == "--dry-run");

    let sources = k210_submit_paths();
    println!("submit k210 -> {}", out.display());
    for path in sources {
        println!("  include {path}");
    }
    if dry_run {
        return Ok(());
    }

    if out.exists() {
        fs::remove_dir_all(&out).map_err(|err| err.to_string())?;
    }
    fs::create_dir_all(&out).map_err(|err| err.to_string())?;

    for path in sources {
        copy_path(root, &out, path)?;
    }
    fs::create_dir_all(out.join(".cargo")).map_err(|err| err.to_string())?;
    if root.join("Cargo.lock").exists() {
        fs::copy(root.join("Cargo.lock"), out.join("Cargo.lock")).map_err(|err| err.to_string())?;
    }

    fs::write(out.join("Cargo.toml"), k210_submit_cargo_toml()).map_err(|err| err.to_string())?;
    fs::write(
        out.join(".cargo").join("config.toml"),
        k210_submit_cargo_config(),
    )
    .map_err(|err| err.to_string())?;
    fs::write(
        out.join("rust-toolchain.toml"),
        k210_submit_rust_toolchain(),
    )
    .map_err(|err| err.to_string())?;
    fs::write(out.join("Makefile"), k210_submit_makefile()).map_err(|err| err.to_string())?;
    fs::write(out.join("README.submit.md"), k210_submit_readme()).map_err(|err| err.to_string())?;
    println!("wrote clean K210 submit tree at {}", out.display());
    println!("next: cd {} && make all", out.display());
    Ok(())
}

fn k210_submit_paths() -> &'static [&'static str] {
    &[
        "crates/tx-hal",
        "crates/tx-kernel",
        "crates/tx-substrate",
        "crates/tx-reactor",
        "crates/tx-policy",
        "crates/tx-drivers",
        "crates/tx-subsystems",
        "crates/tx-services",
        "crates/tx-fs",
        "crates/tx-scripts",
        "crates/tx-shims",
        "boards/tx-hal-riscv64-m1dock-mock",
        "boards/tx-kernel-riscv64-m1dock-mock",
    ]
}

fn k210_submit_cargo_toml() -> &'static str {
    r#"[workspace]
resolver = "2"
members = [
    "crates/tx-hal",
    "crates/tx-kernel",
    "crates/tx-substrate",
    "crates/tx-reactor",
    "crates/tx-policy",
    "crates/tx-drivers",
    "crates/tx-subsystems",
    "crates/tx-services",
    "crates/tx-fs",
    "crates/tx-scripts",
    "crates/tx-shims",
    "boards/tx-hal-riscv64-m1dock-mock",
    "boards/tx-kernel-riscv64-m1dock-mock",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://example.invalid/txkernel"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
lto = "thin"
codegen-units = 1
"#
}

fn k210_submit_cargo_config() -> &'static str {
    r#"[build]
target-dir = "target"

[target.riscv64imac-unknown-none-elf]
linker = "rust-lld"
"#
}

fn k210_submit_rust_toolchain() -> &'static str {
    r#"[toolchain]
channel = "nightly"
components = ["rust-src", "llvm-tools-preview"]
targets = ["riscv64imac-unknown-none-elf"]
"#
}

fn k210_submit_makefile() -> &'static str {
    r#"TARGET ?= riscv64imac-unknown-none-elf
PACKAGE ?= tx-kernel-riscv64-m1dock-mock
KERNEL := target/$(TARGET)/release/$(PACKAGE)

.PHONY: all clean check

all: k210.bin

k210.bin:
	cargo build --release -p $(PACKAGE) --target $(TARGET)
	@if command -v rust-objcopy >/dev/null 2>&1; then \
		rust-objcopy -O binary $(KERNEL) k210.bin; \
	elif command -v llvm-objcopy >/dev/null 2>&1; then \
		llvm-objcopy -O binary $(KERNEL) k210.bin; \
	else \
		echo "missing rust-objcopy or llvm-objcopy"; exit 1; \
	fi

check:
	cargo check -p $(PACKAGE) --target $(TARGET)

clean:
	cargo clean
	rm -f k210.bin
"#
}

fn k210_submit_readme() -> &'static str {
    r#"# txKernel K210 Submit Tree

This directory is generated by:

```sh
cargo xtask submit k210
```

It is intentionally smaller than the main txKernel workspace. It contains only
the Rust crates and M1 Dock board crates needed by the contest-facing Makefile.

The contest contract is:

```sh
make all
```

which must produce `k210.bin` in this directory.

Current caveat: this tree uses the `tx-kernel-riscv64-m1dock-mock` package until
the real K210/M1 Dock HAL replaces the mock boot path.
"#
}

fn copy_path(root: &Path, out: &Path, relative_path: &str) -> Result<()> {
    let src = root.join(relative_path);
    let dst = out.join(relative_path);
    if !src.exists() {
        return Err(format!("missing source path {}", src.display()));
    }
    if src.is_dir() {
        copy_dir_contents(&src, &dst)
    } else {
        if let Some(parent) = dst.parent() {
            fs::create_dir_all(parent).map_err(|err| err.to_string())?;
        }
        fs::copy(src, dst).map_err(|err| err.to_string())?;
        Ok(())
    }
}
