//! `cargo xtask syscall …` — query the wired-syscall map.
//!
//! Treats `crates/tx-shims/src/linux_syscall/{numbers,mod}.rs` as the
//! **single source of truth** for syscall progress. Parses both files,
//! cross-references them, and exposes three things:
//!
//! 1. Read-side queries: `list`, `info`, `status` — what's wired today.
//! 2. Doc sync: `sync` regenerates the auto-maintained section of
//!    `docs/progress/SYSCALL_STATUS.md` between sentinel comments;
//!    `sync --check` is the CI gate (returns nonzero on drift).
//! 3. Pick guidance: `pick` parses the high-stakes table out of the
//!    same doc and prints the top rows so a new task can be scoped
//!    before any code is touched.
//!
//! This module is intentionally regex-free and tolerant of
//! whitespace / comment noise — see [`parse_numbers`] and
//! [`parse_dispatch`].

use std::collections::BTreeMap;
use std::fs;
use std::path::{Path, PathBuf};

use crate::syscall_ref::{
    extra_locals, load_reference, number_mismatches, reference_by_local_name, true_missing,
    LocalNr, LINUX_REF_SUBMODULE, RV64_REFERENCE_JSON, RV64_REFERENCE_URL,
};
use crate::Result;

const NUMBERS_REL: &str = "crates/tx-shims/src/linux_syscall/numbers.rs";
const DISPATCH_REL: &str = "crates/tx-shims/src/linux_syscall/mod.rs";
const STATUS_DOC_REL: &str = "docs/progress/SYSCALL_STATUS.md";
const HANDLER_DIR_REL: &str = "crates/tx-shims/src/linux_syscall";

/// Begin/end sentinels for the auto-maintained section in `SYSCALL_STATUS.md`.
/// `sync` rewrites everything strictly between these two lines.
const BEGIN_SENTINEL: &str =
    "<!-- BEGIN syscall-auto-table (generated by `cargo xtask syscall sync`) -->";
const END_SENTINEL: &str = "<!-- END syscall-auto-table -->";

/// One row of the syscall map.
#[derive(Clone, Debug)]
struct Entry {
    /// Constant name without the `NR_` prefix (e.g. `READ`, `OPENAT`).
    name: String,
    /// Linux RV64 generic syscall number.
    nr: u64,
    /// Status — see [`Status`].
    status: Status,
}

impl Entry {
    fn local_nr(&self) -> LocalNr {
        LocalNr {
            name: self.name.clone(),
            nr: self.nr,
        }
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
enum Status {
    /// Dispatched in `mod.rs` with a handler function.
    Dispatched {
        handler: String,
        is_async: bool,
        /// `true` if the handler body returns `ENOSYS` literally and is
        /// otherwise short (heuristic — the stub catalog in
        /// `SYSCALL_STATUS.md` is the human-checked authority).
        likely_stub: bool,
    },
    /// Dispatched directly in `mod.rs` without a named `sys_*` helper.
    Inline { likely_stub: bool },
    /// `NR_` constant defined in `numbers.rs` but no dispatch arm.
    DefinedNotDispatched,
}

impl Status {
    fn label(&self) -> &'static str {
        match self {
            Status::Dispatched {
                likely_stub: true, ..
            } => "stub",
            Status::Inline { likely_stub: true } => "stub",
            Status::Inline { .. } => "wired",
            Status::Dispatched { is_async: true, .. } => "async",
            Status::Dispatched { .. } => "wired",
            Status::DefinedNotDispatched => "defined",
        }
    }
}

/// Parse `numbers.rs` for every `pub const NR_<NAME>: u64 = <NUM>;`.
fn parse_numbers(text: &str) -> BTreeMap<String, u64> {
    let mut out = BTreeMap::new();
    for line in text.lines() {
        let trimmed = line.trim_start();
        let Some(rest) = trimmed.strip_prefix("pub const NR_") else {
            continue;
        };
        // `NAME: u64 = NUM;` (with possible trailing comment)
        let Some((name, after_name)) = rest.split_once(':') else {
            continue;
        };
        let Some((_ty, rhs)) = after_name.split_once('=') else {
            continue;
        };
        // Strip trailing `;` and any comment after.
        let value_part = rhs.trim().trim_end_matches(';').trim();
        let value_part = value_part.split("//").next().unwrap_or(value_part).trim();
        let value_part = value_part.trim_end_matches(';').trim();
        let Ok(nr) = value_part.parse::<u64>() else {
            continue;
        };
        out.insert(name.trim().to_string(), nr);
    }
    out
}

/// Parse `mod.rs` for dispatch arms matching `NR_<NAME>`.
///
/// Recognises three shapes:
///
/// ```text
///   NR_FOO => sys_foo(...),
///   nr if nr == NR_FOO => sys_foo(...),
///   nr if nr == NR_FOO => {
///       sys_foo(...)
///           .await
///   }
/// ```
///
/// For the multi-line block form the handler may sit on a later line.
/// The parser walks forward until it finds the first `sys_<…>` token
/// inside the arm or hits the next arm's `NR_` reference.
fn parse_dispatch(text: &str) -> BTreeMap<String, DispatchArm> {
    let mut out: BTreeMap<String, DispatchArm> = BTreeMap::new();
    let lines: Vec<&str> = text.lines().collect();
    for (i, raw) in lines.iter().enumerate() {
        let line = raw.trim_start();
        // Skip `use` imports — they list NR_* without `=>`.
        if line.starts_with("use ") {
            continue;
        }
        let Some(arrow) = line.find("=>") else {
            continue;
        };
        let lhs = &line[..arrow];
        // The arm's NR_ token lives on the LHS. Find the *last* one (skip
        // any `nr if nr == NR_FOO` shape's noise word `NR_FOO`).
        let Some(nr_pos) = lhs.rfind("NR_") else {
            continue;
        };
        let after_nr = &lhs[nr_pos + 3..];
        let name_end = after_nr
            .find(|c: char| !c.is_ascii_alphanumeric() && c != '_')
            .unwrap_or(after_nr.len());
        let name = &after_nr[..name_end];
        if name.is_empty() {
            continue;
        }

        // Scan forward starting at the same line's RHS for the first
        // `sys_<…>(` token. If we don't find one before reaching another
        // arm's `=>` or the end of the match, give up on this entry.
        let mut arm_text = String::new();
        let mut scan = &line[arrow + 2..];
        let mut handler: Option<String> = None;
        let mut local_idx = i;
        loop {
            arm_text.push_str(scan);
            arm_text.push('\n');
            if let Some(sys_pos) = scan.find("sys_") {
                let after_sys = &scan[sys_pos + 4..];
                let h_end = after_sys
                    .find(|c: char| !c.is_ascii_alphanumeric() && c != '_')
                    .unwrap_or(after_sys.len());
                // Reject `sys_call_handler_table` style false matches by
                // requiring the next char to be `(`, `:`, `<`, or `.`.
                let after = after_sys[h_end..].chars().next();
                if matches!(after, Some('(' | ':' | '<' | '.')) {
                    handler = Some(format!("sys_{}", &after_sys[..h_end]));
                    break;
                }
                // Otherwise keep scanning past this hit.
                scan = &after_sys[h_end..];
                continue;
            }
            // No sys_ on this line — peek at the next, up to 8 ahead.
            local_idx += 1;
            if local_idx >= lines.len() || local_idx > i + 8 {
                break;
            }
            let next = lines[local_idx];
            // Stop if the next line is another arm (`=>`) or closes the
            // match body (`}` at column zero is the match block close).
            if next.contains("=>") || next.trim_start().starts_with('}') && next.trim() == "}" {
                break;
            }
            scan = next;
        }
        let arm = match handler {
            Some(h) => DispatchArm::Handler(h),
            None => DispatchArm::Inline {
                likely_stub: arm_text.contains("ENOSYS") || arm_text.contains("ENOSYS_VALUE"),
            },
        };
        out.entry(name.to_string()).or_insert(arm);
    }
    out
}

#[derive(Clone, Debug)]
enum DispatchArm {
    Handler(String),
    Inline { likely_stub: bool },
}

/// Walk every `.rs` in the handler directory looking for the named
/// `fn sys_<…>`. Returns `(is_async, body_text)` — body is the first ~50
/// lines after the signature, used by the stub heuristic.
fn locate_handler(handler_dir: &Path, handler: &str) -> Option<(bool, String)> {
    let mut hits = Vec::new();
    for entry in fs::read_dir(handler_dir).ok()? {
        let entry = entry.ok()?;
        let path = entry.path();
        if path.extension().and_then(|e| e.to_str()) != Some("rs") {
            continue;
        }
        let Ok(text) = fs::read_to_string(&path) else {
            continue;
        };
        // Find `fn <handler>(` or `fn <handler><`.
        let needle = format!("fn {handler}");
        let Some(pos) = text.find(&needle) else {
            continue;
        };
        // Confirm the char after the handler name is not alphanumeric.
        let after = &text[pos + needle.len()..];
        let bad_continuation = after
            .chars()
            .next()
            .is_some_and(|c| c.is_ascii_alphanumeric() || c == '_');
        if bad_continuation {
            continue;
        }
        // Detect async by walking backwards a bit.
        let prelude_start = text[..pos].rfind('\n').map(|n| n + 1).unwrap_or(0);
        let prelude = &text[prelude_start..pos];
        let is_async = prelude.contains("async fn") || prelude.contains("async ");
        // Pull up to 60 lines of body for the stub heuristic.
        let body_start = pos;
        let mut body_end = body_start;
        for (i, ch) in text[body_start..].char_indices() {
            if ch == '\n' {
                body_end = body_start + i;
                if text[body_start..body_end].matches('\n').count() >= 60 {
                    break;
                }
            }
        }
        hits.push((is_async, text[body_start..body_end].to_string()));
    }
    hits.into_iter().next()
}

/// Heuristic: does this handler body look like a `-ENOSYS` stub?
///
/// Two signatures count as "yes":
/// 1. The body mentions `ENOSYS` AND mentions `Error(` close by, AND
///    has ≤ 12 non-empty non-comment lines after the `fn` opener.
/// 2. The body contains `unimplemented!()` or `todo!()`.
fn is_likely_stub(body: &str) -> bool {
    if body.contains("unimplemented!()") || body.contains("todo!()") {
        return true;
    }
    let mentions_enosys = body.contains("ENOSYS");
    let mentions_error = body.contains("Error(") || body.contains("err(Errno::ENOSYS");
    if !(mentions_enosys && mentions_error) {
        return false;
    }
    let active_lines = body
        .lines()
        .filter(|l| {
            let t = l.trim();
            !t.is_empty() && !t.starts_with("//")
        })
        .count();
    active_lines <= 14
}

/// Build the full Entry list by cross-referencing numbers.rs and mod.rs
/// and consulting the handler files for async/stub status.
fn collect_entries(root: &Path) -> Result<Vec<Entry>> {
    let numbers_text = fs::read_to_string(root.join(NUMBERS_REL))
        .map_err(|e| format!("read {NUMBERS_REL}: {e}"))?;
    let dispatch_text = fs::read_to_string(root.join(DISPATCH_REL))
        .map_err(|e| format!("read {DISPATCH_REL}: {e}"))?;
    let numbers = parse_numbers(&numbers_text);
    let dispatch = parse_dispatch(&dispatch_text);
    let handler_dir = root.join(HANDLER_DIR_REL);

    let mut out = Vec::with_capacity(numbers.len());
    for (name, nr) in numbers {
        let status = match dispatch.get(&name) {
            Some(DispatchArm::Handler(handler)) => {
                let (is_async, likely_stub) = match locate_handler(&handler_dir, handler) {
                    Some((is_async, body)) => (is_async, is_likely_stub(&body)),
                    None => (false, false),
                };
                Status::Dispatched {
                    handler: handler.clone(),
                    is_async,
                    likely_stub,
                }
            }
            Some(DispatchArm::Inline { likely_stub }) => Status::Inline {
                likely_stub: *likely_stub,
            },
            None => Status::DefinedNotDispatched,
        };
        out.push(Entry { name, nr, status });
    }
    Ok(out)
}

// ---------------------------------------------------------------------------
// Subcommand: `syscall list`
// ---------------------------------------------------------------------------

fn cmd_list(root: &Path, args: &[String]) -> Result<()> {
    let entries = collect_entries(root)?;
    let json = args.iter().any(|a| a == "--json");
    let filter = args
        .iter()
        .skip_while(|a| *a != "--filter")
        .nth(1)
        .map(|s| s.as_str())
        .unwrap_or("all");

    let kept: Vec<&Entry> = entries
        .iter()
        .filter(|e| match filter {
            "all" => true,
            "wired" => matches!(
                &e.status,
                Status::Dispatched {
                    likely_stub: false,
                    ..
                }
            ),
            "stub" => matches!(
                &e.status,
                Status::Dispatched {
                    likely_stub: true,
                    ..
                } | Status::Inline { likely_stub: true }
            ),
            "defined" => matches!(&e.status, Status::DefinedNotDispatched),
            "async" => matches!(&e.status, Status::Dispatched { is_async: true, .. }),
            _ => true,
        })
        .collect();

    if json {
        // Tiny hand-rolled JSON to avoid serde wiring.
        println!("[");
        for (i, e) in kept.iter().enumerate() {
            let (handler, is_async, likely_stub) = match &e.status {
                Status::Dispatched {
                    handler,
                    is_async,
                    likely_stub,
                } => (handler.as_str(), *is_async, *likely_stub),
                Status::Inline { likely_stub } => ("(inline)", false, *likely_stub),
                Status::DefinedNotDispatched => ("", false, false),
            };
            print!(
                "  {{\"name\":\"{}\",\"nr\":{},\"status\":\"{}\",\"handler\":\"{}\",\"async\":{},\"stub\":{}}}",
                e.name,
                e.nr,
                e.status.label(),
                handler,
                is_async,
                likely_stub,
            );
            if i + 1 < kept.len() {
                println!(",");
            } else {
                println!();
            }
        }
        println!("]");
    } else {
        // Aligned text. Columns: NR, NAME, STATUS, HANDLER.
        let nr_w = kept
            .iter()
            .map(|e| e.nr.to_string().len())
            .max()
            .unwrap_or(3);
        let name_w = kept.iter().map(|e| e.name.len()).max().unwrap_or(8);
        for e in &kept {
            let (handler, _, _) = match &e.status {
                Status::Dispatched {
                    handler,
                    is_async,
                    likely_stub,
                } => (handler.as_str(), *is_async, *likely_stub),
                Status::Inline { likely_stub } => ("(inline)", false, *likely_stub),
                Status::DefinedNotDispatched => ("(no arm)", false, false),
            };
            println!(
                "{:>nr_w$}  NR_{:<name_w$}  {:<7}  {}",
                e.nr,
                e.name,
                e.status.label(),
                handler,
                nr_w = nr_w,
                name_w = name_w,
            );
        }
    }
    Ok(())
}

// ---------------------------------------------------------------------------
// Subcommand: `syscall info <name>`
// ---------------------------------------------------------------------------

fn cmd_info(root: &Path, args: &[String]) -> Result<()> {
    let Some(name) = args.first() else {
        return Err(
            "syscall info needs <name> (e.g. `openat`, with or without `NR_` prefix)".into(),
        );
    };
    let key = name
        .trim_start_matches("NR_")
        .trim_start_matches("nr_")
        .to_ascii_uppercase();
    let entries = collect_entries(root)?;
    let reference = load_reference(root)?;
    let reference_by_name = reference_by_local_name(&reference);
    let Some(e) = entries.iter().find(|e| e.name == key) else {
        if let Some(sys) = reference_by_name.get(&key) {
            println!("NR_{key}: not defined locally");
            println!(
                "  Linux RV64 {}: nr={} symbol={} source={}:{}",
                reference.kernel.version, sys.number, sys.symbol, sys.file, sys.line
            );
            println!("  signature: {}", sys.signature.join(", "));
            return Ok(());
        }
        return Err(format!(
            "no NR_{key} found in {NUMBERS_REL} or Linux RV64 reference"
        ));
    };
    println!("NR_{} = {}", e.name, e.nr);
    match &e.status {
        Status::Dispatched {
            handler,
            is_async,
            likely_stub,
        } => {
            println!("  status:  {}", e.status.label());
            println!(
                "  handler: {}{}",
                handler,
                if *is_async { " (async)" } else { "" }
            );
            println!("  stub:    {likely_stub}");
        }
        Status::Inline { likely_stub } => {
            println!("  status:  {}", e.status.label());
            println!("  handler: (inline dispatch arm)");
            println!("  stub:    {likely_stub}");
        }
        Status::DefinedNotDispatched => {
            println!("  status:  defined (no dispatch arm)");
            println!("  TODO:    wire in {DISPATCH_REL}");
        }
    }
    if let Some(sys) = reference_by_name.get(&e.name) {
        println!(
            "  Linux:  nr={} symbol={} source={}:{}",
            sys.number, sys.symbol, sys.file, sys.line
        );
        println!("  sig:    {}", sys.signature.join(", "));
        if sys.number != e.nr {
            println!("  WARN:   local number differs from Linux RV64 reference");
        }
    } else {
        println!(
            "  Linux:  no matching syscall name in RV64 {}",
            reference.kernel.version
        );
    }
    Ok(())
}

// ---------------------------------------------------------------------------
// Subcommand: `syscall status`
// ---------------------------------------------------------------------------

#[derive(Default)]
struct Counts {
    total_nr: usize,
    dispatched: usize,
    dispatched_async: usize,
    stubs: usize,
    defined_no_arm: usize,
}

fn count(entries: &[Entry]) -> Counts {
    let mut c = Counts::default();
    for e in entries {
        c.total_nr += 1;
        match &e.status {
            Status::Dispatched {
                is_async,
                likely_stub,
                ..
            } => {
                c.dispatched += 1;
                if *is_async {
                    c.dispatched_async += 1;
                }
                if *likely_stub {
                    c.stubs += 1;
                }
            }
            Status::Inline { likely_stub } => {
                c.dispatched += 1;
                if *likely_stub {
                    c.stubs += 1;
                }
            }
            Status::DefinedNotDispatched => {
                c.defined_no_arm += 1;
            }
        }
    }
    c
}

fn cmd_status(root: &Path, _args: &[String]) -> Result<()> {
    let entries = collect_entries(root)?;
    let reference = load_reference(root)?;
    let c = count(&entries);
    let locals: Vec<LocalNr> = entries.iter().map(Entry::local_nr).collect();
    println!("txKernel syscall progress");
    println!("=========================");
    println!("NR_* defined in numbers.rs : {}", c.total_nr);
    println!(
        "Linux RV64 reference       : {} ({})",
        reference.syscalls.len(),
        reference.kernel.version
    );
    println!("dispatched in mod.rs       : {}", c.dispatched);
    println!("  …of which async          : {}", c.dispatched_async);
    println!("  …of which likely stubs   : {}", c.stubs);
    println!("defined but no dispatch arm: {}", c.defined_no_arm);
    println!(
        "true missing vs Linux      : {}",
        true_missing(&locals, &reference).len()
    );
    println!(
        "number mismatches          : {}",
        number_mismatches(&locals, &reference).len()
    );
    println!(
        "local extras               : {}",
        extra_locals(&locals, &reference).len()
    );
    println!();
    println!("Pick targets:  cargo xtask syscall pick");
    println!("List wired:    cargo xtask syscall list --filter wired");
    println!("List stubs:    cargo xtask syscall list --filter stub");
    println!("Sync doc:      cargo xtask syscall sync");
    Ok(())
}

// ---------------------------------------------------------------------------
// Subcommand: `syscall sync` / `sync --check`
// ---------------------------------------------------------------------------

fn render_auto_section(
    entries: &[Entry],
    reference: &crate::syscall_ref::ReferenceTable,
) -> String {
    let c = count(entries);
    let locals: Vec<LocalNr> = entries.iter().map(Entry::local_nr).collect();
    let true_missing = true_missing(&locals, reference);
    let mismatches = number_mismatches(&locals, reference);
    let extras = extra_locals(&locals, reference);
    let mut out = String::new();
    out.push_str(BEGIN_SENTINEL);
    out.push('\n');
    out.push_str(
        &format!(
            "\n_This section is generated by `cargo xtask syscall sync` from\n\
             `crates/tx-shims/src/linux_syscall/{{numbers,mod}}.rs` and the Linux RV64 {} reference\n\
             at `{}` (source: {}). Linux file/line references point into `{}`. Do not edit\n\
             between the BEGIN/END sentinels by hand — your changes will be\n\
             overwritten by the next `sync`. The lint variant\n\
             `cargo xtask lint syscall-status` fails on drift or number mismatch._\n\n",
            reference.kernel.version,
            RV64_REFERENCE_JSON,
            RV64_REFERENCE_URL,
            LINUX_REF_SUBMODULE
        ),
    );
    // Counts summary.
    out.push_str("### Counts (from dispatch table)\n\n");
    out.push_str(&format!(
        "- `pub const NR_*` in numbers.rs: **{}**\n",
        c.total_nr
    ));
    out.push_str(&format!(
        "- Linux RV64 reference syscalls: **{}**\n",
        reference.syscalls.len()
    ));
    out.push_str(&format!(
        "- dispatched in mod.rs: **{}** (of which async: {}, likely-stub: {})\n",
        c.dispatched, c.dispatched_async, c.stubs
    ));
    out.push_str(&format!(
        "- defined but not dispatched: **{}**\n\n",
        c.defined_no_arm
    ));
    out.push_str(&format!(
        "- true missing vs Linux RV64 reference: **{}**\n",
        true_missing.len()
    ));
    out.push_str(&format!(
        "- number mismatches vs Linux RV64 reference: **{}**\n",
        mismatches.len()
    ));
    out.push_str(&format!(
        "- local `NR_*` not in Linux RV64 reference: **{}**\n\n",
        extras.len()
    ));
    if !mismatches.is_empty() {
        out.push_str(&format!("### Number mismatches ({})\n\n", mismatches.len()));
        out.push_str("| `NR_*` | Local # | Linux RV64 # | Linux source |\n");
        out.push_str("|---|---:|---:|---|\n");
        for mismatch in &mismatches {
            out.push_str(&format!(
                "| `NR_{}` | {} | {} | `{}`:{} |\n",
                mismatch.name,
                mismatch.local,
                mismatch.reference,
                mismatch.reference_file,
                mismatch.reference_line
            ));
        }
        out.push('\n');
    }
    // Likely-stub list.
    let stubs: Vec<&Entry> = entries
        .iter()
        .filter(|e| {
            matches!(
                &e.status,
                Status::Dispatched {
                    likely_stub: true,
                    ..
                } | Status::Inline { likely_stub: true }
            )
        })
        .collect();
    if !stubs.is_empty() {
        out.push_str(&format!("### Likely stubs ({})\n\n", stubs.len()));
        out.push_str("Heuristic — body ≤14 non-comment lines mentioning `ENOSYS`/`unimplemented!`/`todo!`. The human-curated `## Already-partial` section above is the authoritative classification; this list highlights candidates for cleanup or for moving into the curated catalog.\n\n");
        for e in stubs {
            let handler = match &e.status {
                Status::Dispatched { handler, .. } => handler.as_str(),
                Status::Inline { .. } => "(inline)",
                _ => "",
            };
            out.push_str(&format!("- `NR_{}` ({}) → `{}`\n", e.name, e.nr, handler));
        }
        out.push('\n');
    }
    // Defined but not dispatched.
    let defined: Vec<&Entry> = entries
        .iter()
        .filter(|e| matches!(&e.status, Status::DefinedNotDispatched))
        .collect();
    if !defined.is_empty() {
        out.push_str(&format!(
            "### Defined in `numbers.rs` but no dispatch arm ({})\n\n",
            defined.len()
        ));
        out.push_str("These have a syscall number constant but no match arm in `mod.rs`. Either wire them up or remove the constant.\n\n");
        for e in defined {
            out.push_str(&format!("- `NR_{}` (nr={})\n", e.name, e.nr));
        }
        out.push('\n');
    }
    if !true_missing.is_empty() {
        out.push_str(&format!(
            "### True missing from local `numbers.rs` ({})\n\n",
            true_missing.len()
        ));
        out.push_str("These are Linux RV64 v6.17 syscalls with no local `NR_*` constant. This is the greenfield backlog; it is distinct from defined-but-not-dispatched.\n\n");
        out.push_str("| Linux # | Name | Signature | Linux source |\n");
        out.push_str("|---:|---|---|---|\n");
        for sys in true_missing.iter().take(160) {
            out.push_str(&format!(
                "| {} | `{}` | `{}` | `{}`:{} |\n",
                sys.number,
                sys.name,
                truncate_md(&sys.signature.join(", "), 90),
                sys.file,
                sys.line
            ));
        }
        if true_missing.len() > 160 {
            out.push_str(&format!(
                "|  | ... | {} more omitted from doc output |  |\n",
                true_missing.len() - 160
            ));
        }
        out.push('\n');
    }
    if !extras.is_empty() {
        out.push_str(&format!(
            "### Local `NR_*` not in Linux RV64 reference ({})\n\n",
            extras.len()
        ));
        out.push_str("These constants do not match a syscall name in the Linux RV64 v6.17 reference. They are usually compatibility aliases, stale cross-arch constants, or local scaffolding and should be justified or removed.\n\n");
        for extra in extras {
            out.push_str(&format!("- `NR_{}` (nr={})\n", extra.name, extra.nr));
        }
        out.push('\n');
    }
    // Full dispatched list (compact).
    out.push_str(&format!(
        "### Dispatched syscalls ({}) — name → handler\n\n",
        c.dispatched
    ));
    out.push_str("Sorted by syscall number. `*` marks `async` handlers; `[stub]` marks bodies the heuristic flagged.\n\n");
    let mut dispatched: Vec<&Entry> = entries
        .iter()
        .filter(|e| matches!(&e.status, Status::Dispatched { .. } | Status::Inline { .. }))
        .collect();
    dispatched.sort_by_key(|e| e.nr);
    out.push_str("| NR | Name | Handler | Lane |\n");
    out.push_str("|---:|---|---|---|\n");
    for e in dispatched {
        match &e.status {
            Status::Dispatched {
                handler,
                is_async,
                likely_stub,
            } => {
                let async_mark = if *is_async { "async" } else { "sync" };
                let stub_mark = if *likely_stub { " [stub]" } else { "" };
                out.push_str(&format!(
                    "| {} | `NR_{}` | `{}` | {}{} |\n",
                    e.nr, e.name, handler, async_mark, stub_mark
                ));
            }
            Status::Inline { likely_stub } => {
                let stub_mark = if *likely_stub { " [stub]" } else { "" };
                out.push_str(&format!(
                    "| {} | `NR_{}` | `(inline)` | sync{} |\n",
                    e.nr, e.name, stub_mark
                ));
            }
            Status::DefinedNotDispatched => {}
        }
    }
    out.push('\n');
    out.push_str(END_SENTINEL);
    out.push('\n');
    out
}

fn truncate_md(s: &str, max: usize) -> String {
    let s = s.replace('|', "\\|").replace('\n', " ");
    if s.len() <= max {
        s
    } else {
        let mut out: String = s.chars().take(max - 1).collect();
        out.push('…');
        out
    }
}

fn write_section(root: &Path, args: &[String]) -> Result<()> {
    let check_only = args.iter().any(|a| a == "--check");
    let entries = collect_entries(root)?;
    let reference = load_reference(root)?;
    let locals: Vec<LocalNr> = entries.iter().map(Entry::local_nr).collect();
    let mismatches = number_mismatches(&locals, &reference);
    let new_section = render_auto_section(&entries, &reference);
    let doc_path: PathBuf = root.join(STATUS_DOC_REL);
    let doc_text =
        fs::read_to_string(&doc_path).map_err(|e| format!("read {STATUS_DOC_REL}: {e}"))?;

    let updated = splice_section(&doc_text, &new_section)?;
    if updated == doc_text {
        if check_only && !mismatches.is_empty() {
            return Err(format!(
                "syscall sync: {} number mismatch(es) against Linux RV64 {}; run `cargo xtask syscall sync` for details",
                mismatches.len(),
                reference.kernel.version
            ));
        }
        if !check_only {
            println!("syscall sync: {STATUS_DOC_REL} already up to date");
        }
        return Ok(());
    }
    if check_only {
        return Err(format!(
            "syscall sync: {STATUS_DOC_REL} is stale.\n\
             Run `cargo xtask syscall sync` to regenerate the auto section\n\
             (between `{BEGIN_SENTINEL}` and `{END_SENTINEL}`)."
        ));
    }
    fs::write(&doc_path, updated).map_err(|e| format!("write {STATUS_DOC_REL}: {e}"))?;
    println!("syscall sync: rewrote auto section in {STATUS_DOC_REL}");
    Ok(())
}

/// Replace (or insert before the trailing `## Doc cross-references` if
/// not yet present) the BEGIN…END block.
fn splice_section(doc: &str, new_section: &str) -> Result<String> {
    if let Some(begin) = doc.find(BEGIN_SENTINEL) {
        let Some(end_rel) = doc[begin..].find(END_SENTINEL) else {
            return Err(
                "syscall sync: found BEGIN sentinel without matching END sentinel".to_string(),
            );
        };
        let end = begin + end_rel + END_SENTINEL.len();
        // Consume the newline that follows the END sentinel if present.
        let end = if doc.as_bytes().get(end) == Some(&b'\n') {
            end + 1
        } else {
            end
        };
        let mut out = String::with_capacity(doc.len() + new_section.len());
        out.push_str(&doc[..begin]);
        out.push_str(new_section);
        out.push_str(&doc[end..]);
        return Ok(out);
    }
    // First-time insertion: put the section before the "## Doc cross-references"
    // heading if it exists, else append to the end.
    let insertion_point = doc
        .find("\n## Doc cross-references")
        .map(|n| n + 1)
        .unwrap_or(doc.len());
    let mut out = String::with_capacity(doc.len() + new_section.len() + 64);
    out.push_str(&doc[..insertion_point]);
    out.push_str("## Auto-maintained syscall table\n\n");
    out.push_str(new_section);
    out.push('\n');
    out.push_str(&doc[insertion_point..]);
    Ok(out)
}

// ---------------------------------------------------------------------------
// Subcommand: `syscall pick`
// ---------------------------------------------------------------------------

fn cmd_pick(root: &Path, _args: &[String]) -> Result<()> {
    let doc_path = root.join(STATUS_DOC_REL);
    let text = fs::read_to_string(&doc_path).map_err(|e| format!("read {STATUS_DOC_REL}: {e}"))?;
    // Slice the high-stakes table out of the doc. Heading is exact;
    // table runs until a blank line after the rows.
    let heading = "## High-stakes directions";
    let Some(start) = text.find(heading) else {
        return Err(format!(
            "{STATUS_DOC_REL} has no `{heading}` section — has the doc been refactored?"
        ));
    };
    // Find the start of the table proper (first `|` after the heading).
    let from_heading = &text[start..];
    let table_start_rel = from_heading
        .find("|---")
        .ok_or_else(|| format!("syscall pick: no markdown table found under `{heading}`"))?;
    // Walk back from `|---` to the previous `|` row (the header).
    let header_start = from_heading[..table_start_rel]
        .rfind("\n|")
        .map(|n| start + n + 1)
        .unwrap_or(start);
    // Table ends at the first blank line after the rows.
    let mut end = start + table_start_rel + 4;
    while let Some(nl) = text[end..].find('\n') {
        let abs = end + nl;
        let next_line_start = abs + 1;
        let next_line_end = text[next_line_start..]
            .find('\n')
            .map(|n| next_line_start + n)
            .unwrap_or(text.len());
        end = next_line_end;
        let next_line = text[next_line_start..next_line_end].trim();
        if next_line.is_empty() {
            break;
        }
        if !next_line.starts_with('|') {
            break;
        }
    }
    println!("High-stakes syscall pick guide");
    println!("==============================");
    println!("Source: {STATUS_DOC_REL}\n");
    println!("{}", &text[header_start..end].trim_end());
    println!();
    println!("Top row is the current best LTP-impact-per-effort.");
    println!("Run `cargo xtask syscall info <name>` for details on a specific syscall.");
    println!(
        "Run `cargo xtask syscall list --filter stub` to see candidates already wired but stubbed."
    );
    Ok(())
}

// ---------------------------------------------------------------------------
// Entry point
// ---------------------------------------------------------------------------

pub(crate) fn syscall(root: &Path, args: Vec<String>) -> Result<()> {
    let Some(sub) = args.first() else {
        return Err(
            "syscall command needs a subcommand: list | info | status | sync | pick".into(),
        );
    };
    let rest = &args[1..];
    match sub.as_str() {
        "list" => cmd_list(root, rest),
        "info" => cmd_info(root, rest),
        "status" => cmd_status(root, rest),
        "sync" => write_section(root, rest),
        "pick" => cmd_pick(root, rest),
        other => Err(format!(
            "unknown syscall subcommand '{other}'; expected list|info|status|sync|pick"
        )),
    }
}
