//! Mechanical syscall-status report.
//!
//! Reads `crates/tx-shims/src/linux_syscall/{numbers.rs, mod.rs}` as the
//! single source of truth for which Linux syscalls are defined (`pub const
//! NR_*`) and which are dispatched (have a match arm in `dispatch()`).
//! Renders an autogenerated section into `docs/progress/SYSCALL_STATUS.md`
//! between grep-stable markers, so the human-curated parts of the doc
//! (priority table, OSComp/LTP coverage, topic categorization) stay
//! editable while the headline counts and the "defined but not dispatched"
//! list track the code automatically.
//!
//! See `tx-ltp-syscall` skill for the workflow this command supports.

use std::collections::BTreeSet;
use std::fs;
use std::path::Path;

use crate::syscall_ref::{
    extra_locals, load_reference, number_mismatches, reference_by_local_name, true_missing,
    LocalNr, LINUX_REF_SUBMODULE, RV64_REFERENCE_JSON, RV64_REFERENCE_URL,
};
use crate::Result;

const STATUS_DOC: &str = "docs/progress/SYSCALL_STATUS.md";
const NUMBERS_RS: &str = "crates/tx-shims/src/linux_syscall/numbers.rs";
const MOD_RS: &str = "crates/tx-shims/src/linux_syscall/mod.rs";

const BEGIN_MARKER: &str =
    "<!-- BEGIN AUTOGEN: syscall-table — `cargo xtask syscall-status --regen` -->";
const END_MARKER: &str = "<!-- END AUTOGEN: syscall-table -->";

#[derive(Debug, Clone)]
struct Entry {
    /// Bare name without `NR_` prefix, e.g. `WRITE`.
    name: String,
    /// Numeric syscall number from `numbers.rs`.
    nr: u64,
    /// First line of the leading `///` doc comment, trimmed.
    summary: String,
}

impl Entry {
    fn local_nr(&self) -> LocalNr {
        LocalNr {
            name: self.name.clone(),
            nr: self.nr,
        }
    }
}

pub(crate) fn syscall_status(root: &Path, args: Vec<String>) -> Result<()> {
    let mut regen = false;
    let mut check = false;
    let mut list_missing = false;
    let mut targets: Vec<String> = Vec::new();
    for a in args {
        match a.as_str() {
            "--regen" => regen = true,
            "--check" => check = true,
            "--list-missing" => list_missing = true,
            "-h" | "--help" => {
                print_help();
                return Ok(());
            }
            other if other.starts_with("--") => return Err(format!("unknown flag '{other}'")),
            other => targets.push(other.to_string()),
        }
    }

    let entries = parse_entries(root)?;
    let dispatched = parse_dispatched(root)?;
    let reference = load_reference(root)?;

    if regen {
        return regen_status(root, &entries, &dispatched, &reference);
    }
    if check {
        return check_status(root, &entries, &dispatched, &reference);
    }
    if list_missing {
        return print_missing(&entries, &dispatched, &reference);
    }
    if !targets.is_empty() {
        for t in &targets {
            print_one(t, &entries, &dispatched, &reference);
        }
        return Ok(());
    }
    print_brief(&entries, &dispatched, &reference);
    Ok(())
}

// ---------------------------------------------------------------------------
// Parsing
// ---------------------------------------------------------------------------

fn parse_entries(root: &Path) -> Result<Vec<Entry>> {
    let text =
        fs::read_to_string(root.join(NUMBERS_RS)).map_err(|e| format!("{NUMBERS_RS}: {e}"))?;

    let mut entries = Vec::new();
    let mut pending_docs: Vec<String> = Vec::new();

    for line in text.lines() {
        let trimmed = line.trim_start();
        if let Some(rest) = trimmed.strip_prefix("/// ") {
            pending_docs.push(rest.trim().to_string());
            continue;
        }
        if trimmed.starts_with("///") {
            // Empty doc line.
            pending_docs.push(String::new());
            continue;
        }
        if let Some((name, nr)) = parse_nr_decl(trimmed) {
            let summary = pending_docs
                .iter()
                .find(|s| !s.is_empty())
                .cloned()
                .unwrap_or_else(|| "(no doc)".to_string());
            entries.push(Entry { name, nr, summary });
            pending_docs.clear();
            continue;
        }
        // Any non-doc, non-decl line resets pending docs (so we don't
        // pull doc comments across blank-line gaps from earlier items).
        if !trimmed.is_empty() && !trimmed.starts_with("//") {
            pending_docs.clear();
        }
    }

    entries.sort_by(|a, b| a.name.cmp(&b.name));
    Ok(entries)
}

/// Parse `pub const NR_<NAME>: u64 = <N>;` (with optional `pub(crate)` and
/// trailing comment). Returns `(NAME, N)` on match.
fn parse_nr_decl(line: &str) -> Option<(String, u64)> {
    let line = line.trim();
    let rest = line
        .strip_prefix("pub const NR_")
        .or_else(|| line.strip_prefix("pub(crate) const NR_"))?;
    let colon = rest.find(':')?;
    let name = rest[..colon].trim().to_string();
    let after_eq = rest[colon..].split_once('=')?.1.trim();
    let num_str: String = after_eq
        .chars()
        .take_while(|c| c.is_ascii_digit())
        .collect();
    if num_str.is_empty() {
        return None;
    }
    let nr = num_str.parse().ok()?;
    Some((name, nr))
}

/// Collect `NR_<NAME>` identifiers that appear in dispatch *arms* (not in
/// `use` import blocks). Match-arm shapes the code uses today:
///   `NR_X =>`
///   `nr if nr == NR_X =>`
fn parse_dispatched(root: &Path) -> Result<BTreeSet<String>> {
    let text = fs::read_to_string(root.join(MOD_RS)).map_err(|e| format!("{MOD_RS}: {e}"))?;

    let mut out = BTreeSet::new();
    let mut depth_in_use: i32 = 0;
    for raw in text.lines() {
        let line = raw.trim_start();
        // Track multi-line `use ... { NR_X, ... };` blocks so we don't
        // pick up imports as if they were dispatch arms.
        if line.starts_with("use ") && line.contains('{') && !line.contains('}') {
            depth_in_use += 1;
            continue;
        }
        if depth_in_use > 0 {
            if line.contains("};") || line.contains('}') {
                depth_in_use = depth_in_use.saturating_sub(1);
            }
            continue;
        }
        if line.starts_with("use ") {
            continue;
        }
        // Pattern 1: `NR_X =>` at start of arm
        if let Some(name) = arm_lhs_name(line) {
            out.insert(name);
            continue;
        }
        // Pattern 2: `nr if nr == NR_X =>`
        if let Some(name) = guarded_arm_name(line) {
            out.insert(name);
        }
    }
    Ok(out)
}

fn arm_lhs_name(line: &str) -> Option<String> {
    // Look for `NR_<NAME> =>` at the start of the trimmed line. Reject if
    // followed by anything before `=>` other than whitespace + identifier
    // tail.
    let rest = line.strip_prefix("NR_")?;
    let arrow = rest.find("=>")?;
    let head = rest[..arrow].trim_end();
    if head
        .chars()
        .all(|c| c.is_ascii_uppercase() || c.is_ascii_digit() || c == '_')
        && !head.is_empty()
    {
        Some(head.to_string())
    } else {
        None
    }
}

fn guarded_arm_name(line: &str) -> Option<String> {
    let idx = line.find("nr == NR_")?;
    let after = &line[idx + "nr == NR_".len()..];
    let name: String = after
        .chars()
        .take_while(|c| c.is_ascii_uppercase() || c.is_ascii_digit() || *c == '_')
        .collect();
    if name.is_empty() {
        None
    } else {
        Some(name)
    }
}

// ---------------------------------------------------------------------------
// Rendering
// ---------------------------------------------------------------------------

fn render_autogen(
    entries: &[Entry],
    dispatched: &BTreeSet<String>,
    reference: &crate::syscall_ref::ReferenceTable,
) -> String {
    let total = entries.len();
    let dispatched_count = entries
        .iter()
        .filter(|e| dispatched.contains(&e.name))
        .count();
    let missing: Vec<&Entry> = entries
        .iter()
        .filter(|e| !dispatched.contains(&e.name))
        .collect();
    let locals: Vec<LocalNr> = entries.iter().map(Entry::local_nr).collect();
    let true_missing = true_missing(&locals, reference);
    let number_mismatches = number_mismatches(&locals, reference);
    let extra_locals = extra_locals(&locals, reference);

    let mut out = String::new();
    out.push_str("### Mechanical status (autogenerated)\n\n");
    out.push_str(&format!(
        "_Counts read from `crates/tx-shims/src/linux_syscall/{{numbers.rs, mod.rs}}` and checked against Linux RV64 {} from `{}` (source: {}). Linux file/line references point into `{}`._\n",
        reference.kernel.version, RV64_REFERENCE_JSON, RV64_REFERENCE_URL, LINUX_REF_SUBMODULE
    ));
    out.push_str(
        "_Run `cargo xtask syscall-status --regen` to refresh; `--check` to lint in CI._\n\n",
    );
    out.push_str(&format!("- **`NR_*` defined:** {total}\n"));
    out.push_str(&format!(
        "- **Linux RV64 reference syscalls:** {}\n",
        reference.syscalls.len()
    ));
    out.push_str(&format!(
        "- **Dispatched (has a match arm):** {dispatched_count}\n"
    ));
    out.push_str(&format!(
        "- **Defined but not dispatched:** {} — see list below\n\n",
        missing.len()
    ));
    out.push_str(&format!(
        "- **True missing vs Linux RV64 reference:** {}\n",
        true_missing.len()
    ));
    out.push_str(&format!(
        "- **Number mismatches vs Linux RV64 reference:** {}\n",
        number_mismatches.len()
    ));
    out.push_str(&format!(
        "- **Local `NR_*` not in Linux RV64 reference:** {}\n\n",
        extra_locals.len()
    ));

    if !number_mismatches.is_empty() {
        out.push_str("#### Number mismatches\n\n");
        out.push_str("Local constants in `numbers.rs` whose value differs from the Linux RV64 reference. These should be fixed before relying on syscall-status counts.\n\n");
        out.push_str("| `NR_*` | Local # | Linux RV64 # | Linux source |\n");
        out.push_str("|---|---:|---:|---|\n");
        for mismatch in &number_mismatches {
            out.push_str(&format!(
                "| `NR_{}` | {} | {} | `{}`:{} |\n",
                mismatch.name,
                mismatch.local,
                mismatch.reference,
                mismatch.reference_file,
                mismatch.reference_line
            ));
        }
        out.push('\n');
    }

    if missing.is_empty() {
        out.push_str("_All defined `NR_*` are wired in `dispatch()`._\n");
    } else {
        out.push_str("#### Defined but not dispatched\n\n");
        out.push_str("These syscalls have a `pub const NR_*` in `numbers.rs` but no match arm in `dispatch()`. Closing them is usually cheaper than greenfield work — ABI numbering and one-line intent already exist.\n\n");
        out.push_str("| `NR_*` | # | Summary |\n");
        out.push_str("|---|---:|---|\n");
        for e in missing {
            let s = truncate_summary(&e.summary, 80);
            out.push_str(&format!("| `NR_{}` | {} | {} |\n", e.name, e.nr, s));
        }
    }
    out.push('\n');

    if !true_missing.is_empty() {
        out.push_str("#### True missing from local `numbers.rs`\n\n");
        out.push_str("Linux RV64 v6.17 syscalls that have no local `NR_*` constant. This is the greenfield backlog; it is distinct from defined-but-not-dispatched.\n\n");
        out.push_str("| Linux # | Name | Signature | Linux source |\n");
        out.push_str("|---:|---|---|---|\n");
        for sys in true_missing.iter().take(120) {
            out.push_str(&format!(
                "| {} | `{}` | `{}` | `{}`:{} |\n",
                sys.number,
                sys.name,
                truncate_summary(&sys.signature.join(", "), 88),
                sys.file,
                sys.line
            ));
        }
        if true_missing.len() > 120 {
            out.push_str(&format!(
                "|  | ... | {} more omitted from doc; run `cargo xtask syscall-status --list-missing --all` |  |\n",
                true_missing.len() - 120
            ));
        }
        out.push('\n');
    }

    if !extra_locals.is_empty() {
        out.push_str("#### Local `NR_*` not in Linux RV64 reference\n\n");
        out.push_str("These constants are not present by syscall name in the Linux RV64 v6.17 table. They are usually compatibility aliases, stale cross-arch constants, or local scaffolding and should be justified or removed.\n\n");
        out.push_str("| `NR_*` | Local # |\n");
        out.push_str("|---|---:|\n");
        for local in extra_locals {
            out.push_str(&format!("| `NR_{}` | {} |\n", local.name, local.nr));
        }
    }
    out
}

fn truncate_summary(s: &str, max: usize) -> String {
    let s = s.replace('|', "\\|").replace('\n', " ");
    if s.len() <= max {
        s
    } else {
        let mut t: String = s.chars().take(max - 1).collect();
        t.push('…');
        t
    }
}

// ---------------------------------------------------------------------------
// File splicing
// ---------------------------------------------------------------------------

fn splice_autogen(doc: &str, generated: &str) -> Result<String> {
    let begin = doc
        .find(BEGIN_MARKER)
        .ok_or_else(|| format!("{STATUS_DOC}: missing BEGIN marker `{BEGIN_MARKER}`"))?;
    let after_begin = begin + BEGIN_MARKER.len();
    let end_rel = doc[after_begin..]
        .find(END_MARKER)
        .ok_or_else(|| format!("{STATUS_DOC}: missing END marker `{END_MARKER}` after BEGIN"))?;
    let end = after_begin + end_rel;

    let mut out = String::with_capacity(doc.len() + generated.len());
    out.push_str(&doc[..after_begin]);
    out.push_str("\n\n");
    out.push_str(generated);
    out.push('\n');
    out.push_str(&doc[end..]);
    Ok(out)
}

fn regen_status(
    root: &Path,
    entries: &[Entry],
    dispatched: &BTreeSet<String>,
    reference: &crate::syscall_ref::ReferenceTable,
) -> Result<()> {
    let path = root.join(STATUS_DOC);
    let original = fs::read_to_string(&path).map_err(|e| format!("{STATUS_DOC}: {e}"))?;
    let generated = render_autogen(entries, dispatched, reference);
    let updated = splice_autogen(&original, &generated)?;
    if original == updated {
        println!("syscall-status: {STATUS_DOC} already up to date");
        return Ok(());
    }
    fs::write(&path, updated).map_err(|e| format!("{STATUS_DOC}: {e}"))?;
    println!("syscall-status: regenerated autogen section in {STATUS_DOC}");
    Ok(())
}

fn check_status(
    root: &Path,
    entries: &[Entry],
    dispatched: &BTreeSet<String>,
    reference: &crate::syscall_ref::ReferenceTable,
) -> Result<()> {
    let path = root.join(STATUS_DOC);
    let original = fs::read_to_string(&path).map_err(|e| format!("{STATUS_DOC}: {e}"))?;
    let generated = render_autogen(entries, dispatched, reference);
    let expected = splice_autogen(&original, &generated)?;
    let locals: Vec<LocalNr> = entries.iter().map(Entry::local_nr).collect();
    let mismatches = number_mismatches(&locals, reference);
    if original == expected && mismatches.is_empty() {
        println!("syscall-status: {STATUS_DOC} autogen section is current");
        Ok(())
    } else if !mismatches.is_empty() {
        Err(format!(
            "{STATUS_DOC}: {} syscall number mismatch(es) against Linux RV64 {} — run `cargo xtask syscall-status --regen` for details",
            mismatches.len(),
            reference.kernel.version
        ))
    } else {
        Err(format!(
            "{STATUS_DOC} autogen section is stale — run `cargo xtask syscall-status --regen`"
        ))
    }
}

// ---------------------------------------------------------------------------
// Console reports
// ---------------------------------------------------------------------------

fn print_brief(
    entries: &[Entry],
    dispatched: &BTreeSet<String>,
    reference: &crate::syscall_ref::ReferenceTable,
) {
    let total = entries.len();
    let count = entries
        .iter()
        .filter(|e| dispatched.contains(&e.name))
        .count();
    let missing = total - count;
    let locals: Vec<LocalNr> = entries.iter().map(Entry::local_nr).collect();
    let true_missing_count = true_missing(&locals, reference).len();
    let mismatch_count = number_mismatches(&locals, reference).len();
    let extra_count = extra_locals(&locals, reference).len();
    println!("txKernel syscall status");
    println!("=======================");
    println!("  NR_* defined            : {total}");
    println!(
        "  Linux RV64 reference    : {} ({})",
        reference.syscalls.len(),
        reference.kernel.version
    );
    println!("  Dispatched              : {count}");
    println!("  Defined but undispatched: {missing}");
    println!("  True missing vs Linux   : {true_missing_count}");
    println!("  Number mismatches       : {mismatch_count}");
    println!("  Local extras            : {extra_count}");
    println!();
    println!("Detail commands:");
    println!("  cargo xtask syscall-status <NAME>   # info for one syscall (e.g. fork, sendfile)");
    println!("  cargo xtask syscall-status --list-missing");
    println!("  cargo xtask syscall-status --regen  # refresh autogen in {STATUS_DOC}");
    println!("  cargo xtask syscall-status --check  # lint mode (CI)");
    println!();
    println!("Priority and OSComp/LTP coverage: see {STATUS_DOC}.");
}

fn print_missing(
    entries: &[Entry],
    dispatched: &BTreeSet<String>,
    reference: &crate::syscall_ref::ReferenceTable,
) -> Result<()> {
    let missing: Vec<&Entry> = entries
        .iter()
        .filter(|e| !dispatched.contains(&e.name))
        .collect();
    let locals: Vec<LocalNr> = entries.iter().map(Entry::local_nr).collect();
    let true_missing = true_missing(&locals, reference);
    if missing.is_empty() {
        println!("syscall-status: every defined NR_* has a dispatch arm.");
    } else {
        println!("Defined but not dispatched ({}):", missing.len());
        for e in &missing {
            let s = truncate_summary(&e.summary, 70);
            println!("  NR_{:<28} {:>4}  {s}", e.name, e.nr);
        }
    }
    println!();
    println!(
        "True missing from Linux RV64 {} ({}):",
        reference.kernel.version,
        true_missing.len()
    );
    for sys in true_missing.iter().take(80) {
        println!(
            "  {:>4}  {:<28} {}:{}",
            sys.number, sys.name, sys.file, sys.line
        );
    }
    if true_missing.len() > 80 {
        println!(
            "  ... {} more (run `cargo xtask syscall-status --regen` for the doc table)",
            true_missing.len() - 80
        );
    }
    Ok(())
}

fn print_one(
    target: &str,
    entries: &[Entry],
    dispatched: &BTreeSet<String>,
    reference: &crate::syscall_ref::ReferenceTable,
) {
    let needle = target.trim().trim_start_matches("NR_").to_ascii_uppercase();
    let hit = entries.iter().find(|e| e.name == needle);
    let reference_by_name = reference_by_local_name(reference);
    match hit {
        None => {
            println!("{target}: no NR_{needle} found in {NUMBERS_RS}");
            if let Some(reference) = reference_by_name.get(&needle) {
                println!(
                    "  Linux RV64 {}: nr={} symbol={} source={}:{}",
                    reference.name,
                    reference.number,
                    reference.symbol,
                    reference.file,
                    reference.line
                );
                println!("  signature: {}", reference.signature.join(", "));
            } else {
                println!("  (not found in local numbers.rs or Linux RV64 reference)");
            }
        }
        Some(e) => {
            let state = if dispatched.contains(&e.name) {
                "dispatched"
            } else {
                "DEFINED BUT NOT DISPATCHED"
            };
            println!("NR_{}", e.name);
            println!("  number  : {}", e.nr);
            println!("  state   : {state}");
            println!("  summary : {}", e.summary);
            if let Some(reference) = reference_by_name.get(&e.name) {
                println!(
                    "  Linux   : nr={} symbol={} source={}:{}",
                    reference.number, reference.symbol, reference.file, reference.line
                );
                if reference.number != e.nr {
                    println!("  WARNING : local number differs from Linux RV64 reference");
                }
            } else {
                println!(
                    "  Linux   : no matching syscall name in RV64 {}",
                    reference.kernel.version
                );
            }
            println!();
            println!("Next steps:");
            if dispatched.contains(&e.name) {
                println!("  - dispatch arm exists; inspect body in {MOD_RS} to check for stubs");
                println!("  - if the arm returns -ENOSYS, the syscall is partial — see");
                println!("    `tx-shell-syscall-fixup` for the observe→fix→verify loop");
            } else {
                println!("  - add a match arm in {MOD_RS} routing to a handler");
                println!("  - load `tx-syscall-dispatch` for lane choice (Immediate / OneShotStepOp / async)");
                println!("  - target an OSComp or LTP test that exercises this syscall");
                println!("    (see {STATUS_DOC} for the gold-standard correctness bar)");
            }
        }
    }
}

fn print_help() {
    println!("usage: cargo xtask syscall-status [<NAME>...] [--regen | --check | --list-missing]");
    println!();
    println!("With no arguments: print headline counts and the detail-command menu.");
    println!("With <NAME>      : print state + numbering + summary for that syscall.");
    println!("--list-missing   : list every defined NR_* that has no dispatch arm.");
    println!("--regen          : refresh the autogen section in {STATUS_DOC}.");
    println!("--check          : fail if the autogen section is stale (CI gate).");
}
