[package]
name = "tx-kernel"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
tx-fs = { path = "../tx-fs" }
tx-hal = { path = "../tx-hal" }
tx-drivers = { path = "../tx-drivers" }
tx-policy = { path = "../tx-policy" }
tx-reactor = { path = "../tx-reactor" }
tx-scripts = { path = "../tx-scripts" }
tx-services = { path = "../tx-services" }
tx-shims = { path = "../tx-shims" }
tx-substrate = { path = "../tx-substrate" }
tx-subsystems = { path = "../tx-subsystems" }

[lib]
path = "src/lib.rs"
test = false
doctest = false
